### ISSUE TITLE
Dedupe `@abacus-network/deploy` and `@abacus-network/hardhat` deploy objects

### ISSUE THREAD

**Issue by yorhodes** [abacus-network/abacus-monorepo#338] opened 2022-04-14 00:08 UTC

**Comment by yorhodes** [comment] 2022-05-12 15:29
1. Remove `TestDeploy`

**Comment by nambrot** [comment] 2022-05-16 22:20
Is this now a dupe of #383 @yorhodes

**Comment by yorhodes** [comment] 2022-05-17 05:14
@nambrot yes, I was looking for this issue...

**Closed** 2022-05-17 20:44 UTC
